services:
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./${FILENAME}:/${FILENAME}:ro"
    env_file:
      - .env

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "8088:8080"
    environment:
      - API_URL=/docs/swagger.yaml
    volumes:
      - "./api:/usr/share/nginx/html/docs"

